=== dainiusjocas/forward_chaining/build/classes/xml/InputDescription.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE data SYSTEM "InputDescription.dtd">

    <data>
    ...
    </data>
-->

<!ELEMENT data (goal|facts|implications)*>
<!ELEMENT implications (implication)*>
<!ELEMENT implication (consequent|antecedent)*>
<!ATTLIST implication
    id CDATA #IMPLIED
  >
<!ELEMENT antecedent (#PCDATA)>
<!ELEMENT consequent (#PCDATA)>
<!ELEMENT facts (fact)*>
<!ELEMENT fact (#PCDATA)>
<!ELEMENT goal (#PCDATA)>

=== dainiusjocas/forward_chaining/demo/4_9_implications.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : 4_9_implications.xml
    Created on : March 13, 2011, 11:43 AM
    Author     : Dainius Jocas, VU MIF, PS#3, 3rd year
    Description:
        Data input file for first excersice of the "Artificial Inteligence"
        course. In this file we will place example with 9 implications.
-->

<!DOCTYPE data SYSTEM "InputDescription.dtd">
<data>
    <implications>
        <implication id="R1">
            <antecedent>D</antecedent>
            <antecedent>C</antecedent>
            <consequent>Z</consequent>
        </implication>
        <implication id="R2">
            <antecedent>C</antecedent>
            <consequent>D</consequent>
        </implication>
        <implication id="R3">
            <antecedent>B</antecedent>
            <consequent>C</consequent>
        </implication>
        <implication id="R4">
            <antecedent>A</antecedent>
            <consequent>B</consequent>
        </implication>
        <implication id="R5">
            <antecedent>D</antecedent>
            <consequent>A</consequent>
        </implication>
        <implication id="R6">
            <antecedent>T</antecedent>
            <consequent>D</consequent>
        </implication>
        <implication id="R7">
            <antecedent>G</antecedent>
            <consequent>A</consequent>
        </implication>
        <implication id="R8">
            <antecedent>H</antecedent>
            <consequent>B</consequent>
        </implication>
        <implication id="R9">
            <antecedent>J</antecedent>
            <consequent>C</consequent>
        </implication>
    </implications>
    <facts>
        <fact>T</fact>
    </facts>
    <goal>Z</goal>
</data>
